CREATE TABLE BOOK
(
    BOOK_ID NUMBER PRIMARY KEY,
    TITLE   VARCHAR(255),
    AUTHOR  VARCHAR(255),
    ISBN    VARCHAR(13)
);

CREATE SEQUENCE SEQ_BOOK_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999;

CREATE INDEX IX_BOOK_ID ON BOOK (BOOK_ID);